#!/usr/bin/env bash

# Restores the latest test DB dump to the test site, and updates it if necessary
echo "Checking that we're good to go..."
fin check-vpn || exit $?

drush=$PROJECT_ROOT/vendor/bin/drush


# use some command-fu to find and restore the newest test dump
# have to use semicolons because drush ssh is dumb
server_code=$(cat << 'EOF'
    latest_dump=$(echo $HOME/backups/test_*.sql | tr ' ' '\n' | tail -n 1) &&
    if [ -z $latest_dump ];
    then
        touch foo;
        echo 'No test database dump to restore' >&2;
        exit 1;
    fi &&

    echo Restoring $latest_dump to test DB &&
    drush=../vendor/bin/drush &&
    $drush sset system.maintenance_mode TRUE &&
    $drush sql-drop &&
    $drush sql-query --file=$latest_dump &&
    $drush updb -y &&
    $drush sset system.maintenance_mode FALSE &&
    echo &&
    echo Test DB restored.

    || echo Failed to restore test DB. >&2
EOF
)

# ssh_cmd=(bash +O nullglob -c "$server_code")
# $drush @self.test --tty ssh "${ssh_cmd[*]}"
$drush @self.test --ssh-options="-t" ssh "sudo -u neuronet bash +O nullglob -c \"$server_code\""
