<?php

/**
 * @file
 * Contains neuronet_misc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function neuronet_misc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the neuronet_misc module.
    case 'help.page.neuronet_misc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds miscellaneous functionality to the NeuroNet website') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_pre_render().
 */
function neuronet_misc_views_pre_render(\Drupal\views\ViewExecutable $view) {
	// Remove old positions
  if($view->id() == 'alumni'){
  	$indexes_to_remove = array();
    foreach($view->result as $value){
    	// it is VERY annoying to get entity reference values in Drupal 8
      $nid = $value->_entity->get('field_profile')->first()->get('entity')->getTarget()->getValue()->get('nid')->value;
      $start_date = $value->_entity->get('field_start_date')->value;
      $index = 0;
      foreach($view->result as $value2){
      	$sub_nid = $value2->_entity->get('field_profile')->first()->get('entity')->getTarget()->getValue()->get('nid')->value;
      	if ($nid == $sub_nid) {		
      		$start_date = $value->_entity->get('field_start_date')->value;
      		$start_date2 = $value2->_entity->get('field_start_date')->value;
      		if (date($start_date2) < date($start_date)) {
      			$indexes_to_remove[] = $index;
      		}
      	}
      	$index++;
      }
    }
    foreach ($indexes_to_remove as $index){
    	unset($view->result[$index]);
    }
  }
}